<?php

namespace Database\Seeders;

use App\Models\Cargo;
use Illuminate\Database\Seeder;

class CargoSeeder extends Seeder
{
    public function run(): void
    {
        $cargos = [
            // Nivel Inicial
            ['codigo' => 100, 'nombre' => 'Supervisor Nivel Inicial.'],
            ['codigo' => 101, 'nombre' => 'Dir. Nivel Inicial-T.C.'],
            ['codigo' => 102, 'nombre' => 'Dir. 1ª Nivel Inicial- T.S.'],
            ['codigo' => 103, 'nombre' => 'Dir. 2ª Nivel Inicial.-T.S.'],
            ['codigo' => 104, 'nombre' => 'Dir. 3ª Nivel Inical.- T.S.'],
            ['codigo' => 105, 'nombre' => 'Vicedir. Nivel Inical.- T.C.'],
            ['codigo' => 106, 'nombre' => 'Vicedir. Nivel Inical. T.S.'],
            ['codigo' => 107, 'nombre' => 'Sec.Nivel Inicial.- T.C.'],
            ['codigo' => 108, 'nombre' => 'Sec. Nivel Inicial. -T-S.'],
            ['codigo' => 109, 'nombre' => 'Mtro.(sección) Nivel Inicial- T.S.'],
            ['codigo' => 110, 'nombre' => 'Mtro.Bibliotecario. - T.S.'],
            ['codigo' => 111, 'nombre' => 'Mtro.DeProyectos especificos - T.S.'],
            ['codigo' => 112, 'nombre' => 'Mtro.Secc.NivelInicial (aux.sala).-T.S.'],
            ['codigo' => 113, 'nombre' => 'Mtro. Aux. Secr.Nivel Inicial- T.S.'],
            ['codigo' => 114, 'nombre' => 'Maestro Tutor.- T.S.'],
            ['codigo' => 115, 'nombre' => 'Hora Cátedra Nivel Inicial.'],
            ['codigo' => 116, 'nombre' => 'Pareja Pedagógica T.S.'],
            // --- EGB 1 y 2 ---
            ['codigo' => 200, 'nombre' => 'Supervisor Nivel EGB 1 Y 2.'],
            ['codigo' => 201, 'nombre' => 'Dir. Pers. Unico EGB 1 Y 2.- T.C.'],
            ['codigo' => 202, 'nombre' => 'Dir. 1ª Nivel EGB 1 Y 2.- T.C.'],
            ['codigo' => 203, 'nombre' => 'Dir. 2ª nivel EGB 1 Y 2.- T.C.'],
            ['codigo' => 204, 'nombre' => 'Dir.3ª Nivel EGB 1 Y 2.- T.C.'],
            ['codigo' => 205, 'nombre' => 'Dir. 1ªNivel EGB 1 Y 2 .- T.S.'],
            ['codigo' => 206, 'nombre' => 'Dir. 2ª Nivel EGB 1 Y 2.- T.S.'],
            ['codigo' => 207, 'nombre' => 'Dir. 3ª Nivel EGB 1 Y 2 .- T.S.'],
            ['codigo' => 208, 'nombre' => 'Vicedir. Nivel EGB 1 Y 2 .- T.C.'],
            ['codigo' => 209, 'nombre' => 'Vicedir. Nivel EGB 1 Y 2.- T.S.'],
            ['codigo' => 210, 'nombre' => 'Sec. Nivel EGB. 1 Y 2. T.C.'],
            ['codigo' => 211, 'nombre' => 'Sec. Nivel EGB 1 Y 2.- T.S.'],
            ['codigo' => 212, 'nombre' => 'Mtro. (año) Nivel EGB. 1 Y 2.- T.S.'],
            ['codigo' => 213, 'nombre' => 'Mtro. Bibliotecario. T.S.'],
            ['codigo' => 214, 'nombre' => 'Mtro. Computación.- T.S.'],
            ['codigo' => 215, 'nombre' => 'Mtro. Domic. Hospit.- T.S.'],
            ['codigo' => 216, 'nombre' => 'Mtro. de Proyectos Especificos.- T.S.'],
            ['codigo' => 217, 'nombre' => 'Mtro. Recuperador.- T.S.'],
            ['codigo' => 218, 'nombre' => 'Mtro. Tutor.- T.S.'],
            ['codigo' => 219, 'nombre' => 'Mtro. (año) Nivel EGB 1 Y 2.- T.C.'],
            ['codigo' => 220, 'nombre' => 'Mtro. Aux. secr. EGB 1 Y 2.- T.S.'],
            ['codigo' => 221, 'nombre' => 'Hora Cátedra Nivel EGB 1 Y 2'],
            ['codigo' => 222, 'nombre' => 'Coord. Ciclo EGB 1Y2-T.C.'],
            ['codigo' => 223, 'nombre' => 'Coord. Ciclo EGB 1Y2-T.S.'],
            ['codigo' => 224, 'nombre' => 'Pareja Pedagógica T.S.'],
            ['codigo' => 230, 'nombre' => 'Maestro Bibliotecario T.C.'],
            ['codigo' => 231, 'nombre' => 'Maestro de Computación T.C.'],
            ['codigo' => 232, 'nombre' => 'Mtro. Domiciliario/Hospitalario T.C.'],
            ['codigo' => 233, 'nombre' => 'Mtro. de Proyectos Especificos T.C.'],
            ['codigo' => 234, 'nombre' => 'Mtro. Recuperador T.C.'],
            ['codigo' => 235, 'nombre' => 'Tutor/a Docente T.C.'],
            ['codigo' => 236, 'nombre' => 'Mtro. Aux. de Secretaría T.C.'],
            // --- Especial ---
            ['codigo' => 300, 'nombre' => 'Supervisor Modalidad Especial.'],
            ['codigo' => 301, 'nombre' => 'Dir. Modalidad Especial - T.C.'],
            ['codigo' => 302, 'nombre' => 'Vicedir. Modalidad Especial - T.C.'],
            ['codigo' => 303, 'nombre' => 'Sec. Modalidad Especial - T.C.'],
            ['codigo' => 304, 'nombre' => 'Docente de Grupo - T.S.'],
            ['codigo' => 305, 'nombre' => 'Docente de Sección - T.S.'],
            ['codigo' => 306, 'nombre' => 'Docente de Ciclo - T.S.'],
            ['codigo' => 307, 'nombre' => 'Docente Bibliotecario. - T.S.'],
            ['codigo' => 308, 'nombre' => 'Docente de Proyectos Especificos - T.S.'],
            ['codigo' => 309, 'nombre' => 'Docente Tutor - T.S.'],
            ['codigo' => 310, 'nombre' => 'Docente Auxiliar de Secretaría - T.S.'],
            ['codigo' => 311, 'nombre' => 'Docente Auxiliar de Grupo - T.S.'],
            ['codigo' => 312, 'nombre' => 'Hora Cátedra Especial'],
            ['codigo' => 313, 'nombre' => 'Enfermero/a - T.S.'],
            ['codigo' => 314, 'nombre' => 'Coordinador/a Pedagógico/a - T.S.'],
            ['codigo' => 315, 'nombre' => 'Coordinador/a Técnico/a - T.S.'],
            ['codigo' => 316, 'nombre' => 'H.C. Docente Equipo Interdisc. Institucional'],
            // --- No Formal ---
            ['codigo' => '400', 'nombre' => 'Supervisor Nivel Jovenes y Adul.'],
            ['codigo' => '401', 'nombre' => 'Dir. Cent. Sec.CENS.- T.S.'],
            ['codigo' => '402', 'nombre' => 'Vicedir. Cent. Sec. CENS -T.S.'],
            ['codigo' => '403', 'nombre' => 'Coord. de Ciclo Cent. Sec. CENS.- T.S.'],
            ['codigo' => '404', 'nombre' => 'Secretario Cent. Sec. CENS.- T.S.'],
            ['codigo' => '405', 'nombre' => 'ProSecretario Cent. Sec. CENS.- T.S.'],
            ['codigo' => '406', 'nombre' => 'Dir. Esc. Nivel Jov.y ad..- T.C.'],
            ['codigo' => '407', 'nombre' => 'Vicedir. Esc. Nivel Jov.y ad..- T.C.'],
            ['codigo' => '408', 'nombre' => 'Sec.Nivel Jovenes y Adultos.- T.C.'],
            ['codigo' => '409', 'nombre' => 'Mtro. Ciclo Nivel Jovenes y Ad.- T.S.'],
            ['codigo' => '410', 'nombre' => 'Mtro.Aux.secr.Nivel jov.y ad.- T.S.'],
            ['codigo' => '411', 'nombre' => 'Bibliotecario Escolar'],
            ['codigo' => '412', 'nombre' => 'Mtro. Proyectos Especificos - T.S.'],
            ['codigo' => '413', 'nombre' => 'Mtro. Computación.- T.S.'],
            ['codigo' => '414', 'nombre' => 'Mtro.p/pers.Priv. De la libertad.- T.S.'],
            ['codigo' => '415', 'nombre' => 'Tutor Docente Nivel Jóvene y Adultos'],
            ['codigo' => '416', 'nombre' => 'Mtro.Activ. Práct.Nivel Jov. Y Ad.'],
            ['codigo' => '417', 'nombre' => 'Auxiliar administrativo docente T.C.'],
            ['codigo' => '418', 'nombre' => 'Jefe de laboratorio.'],
            ['codigo' => '419', 'nombre' => 'Ay. Téc. Trab. Prác.(ATTP)'],
            ['codigo' => '420', 'nombre' => 'Preceptor.'],
            ['codigo' => '421', 'nombre' => 'Hora Cátedra Nivel Jovenes y ad.'],
            ['codigo' => '422', 'nombre' => 'Auxiliar de Secretaría T.S.'],
            ['codigo' => '423', 'nombre' => 'Auxiliar de Secretaría T.C.'],
            ['codigo' => '451', 'nombre' => 'DIRECTOR DE EDUCACIÓN ESPECIAL NO FORMAL T.C.'],
            ['codigo' => '452', 'nombre' => 'VICE DIRECTOR EDUCACION ESPECIAL NO FORMAL T.C.'],
            ['codigo' => '453', 'nombre' => 'SECRETARIO ADMINISTRATIVO EDUCACION ESPECIAL NO FORMAL T.S.'],
            ['codigo' => '454', 'nombre' => 'MAESTRO TUTOR EDUCACIÓN ESPECIAL NO FORMAL T.S.'],
            ['codigo' => '455', 'nombre' => 'TALLERISTA EDICACIÓN ESPECIAL NO FORMAL T.S.'],
            ['codigo' => '456', 'nombre' => 'HORA CÁTEDRA EDUCACIÓN ESPECIAL NO FORMAL'],
            ['codigo' => '457', 'nombre' => 'HORA CATEDRA EDUCACIÓN ESP. NO FORMAL- EQUIPO MULTIDISCIPLINARIO'],
            ['codigo' => '458', 'nombre' => 'DIRECTOR EDUCACIÓN NO FORMAL T.C.'],
            ['codigo' => '459', 'nombre' => 'VICEDIRECTOR EDUCACIÓN NO FORMAL T.C.'],
            ['codigo' => '460', 'nombre' => 'COORDINADOR EDUCACIÓN NO FORMAL T.C.'],
            ['codigo' => '461', 'nombre' => 'SECRETARIO ADMINISTRATIVO EDUCACIÓN NO FORMAL T.C.'],
            ['codigo' => '462', 'nombre' => 'PRECEPTOR EDUCACIÓN NO FORMAL T.C.'],
            ['codigo' => '463', 'nombre' => 'JEFE GENERAL ENSAÑANZA PRÁCTICA EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '464', 'nombre' => 'REGENTE ENSEÑANZA PRACTICA EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '465', 'nombre' => 'COORDINADOR EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '466', 'nombre' => 'SECRETARIO ADMINISTRATIVO EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '467', 'nombre' => 'MAESTRO DE ENSEÑANZA PRÁCTICA JEFE SECCIÓN EDUC. NO FORMAL T.S.'],
            ['codigo' => '468', 'nombre' => 'PROSECRETARIO EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '469', 'nombre' => 'MAESTRO DE ENSAÑANZA PRÁCTICA EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '470', 'nombre' => 'MAESTRO TUTOR EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '471', 'nombre' => 'BIBLIOTECARIO EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '472', 'nombre' => 'PRECEPTOR EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '473', 'nombre' => 'AYUDANTE DE TRABAJOS PRACTICOS (ATTP) EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '474', 'nombre' => 'HORA CÁTEDRA EDUCACIÓN NO FORMAL T.S.'],
            ['codigo' => '475', 'nombre' => 'Auxiliar de Secretaría T.S.'],
            ['codigo' => '476', 'nombre' => 'Auxiliar de Secretaría T.C.'],
            ['codigo' => '500', 'nombre' => 'Supervisor Dptal. de Gabinete P.y A.E.'],
            ['codigo' => '501', 'nombre' => 'Director Dptal. de Gabinete P.y A.E.'],
            ['codigo' => '502', 'nombre' => 'Secretario de Gabinete P.y A.E.'],
            ['codigo' => '503', 'nombre' => 'Asistente Social'],
            ['codigo' => '504', 'nombre' => 'Asistente Educacional'],
            ['codigo' => '505', 'nombre' => 'Psicólogo'],
            ['codigo' => '506', 'nombre' => 'Psicomotricista'],
            ['codigo' => '507', 'nombre' => 'Psicopedagogo'],
            ['codigo' => '508', 'nombre' => 'Músicoterapeuta'],
            ['codigo' => '509', 'nombre' => 'Terapista Ocupacional'],
            ['codigo' => '510', 'nombre' => 'Fonoaudiólogo'],
            ['codigo' => '511', 'nombre' => 'Vicedirector de Clínica Terapéutica GPyAE'],
            ['codigo' => '512', 'nombre' => 'Viced. de Prevención y Promoción GPyAE'],
            ['codigo' => '513', 'nombre' => 'Viced. Equipos Interdiscipl. Escolares GPyAE'],
            ['codigo' => '514', 'nombre' => 'Aux. de Secretaría de Gabinete P.y A.E.'],
            ['codigo' => '600', 'nombre' => 'S.T.S.Niv.Inicial, EGB 1 y 2, Esp. Y Gab.'],
            ['codigo' => '601', 'nombre' => 'S.T.S Nivel EGB 3 y Polim.'],
            ['codigo' => '602', 'nombre' => 'S.T.S.Nivel Jovenes y Adultos.'],
            ['codigo' => '700', 'nombre' => 'Dir. De Biblioteca.-T.C.'],
            ['codigo' => '701', 'nombre' => 'Vice-Director Departamental de Biblioteca'],
            ['codigo' => '702', 'nombre' => 'Secret. Tecn. Administ. Dptal.Bibliotecas'],
            ['codigo' => '703', 'nombre' => 'Supervisión Departamental de Bibliotecas'],
            ['codigo' => '704', 'nombre' => 'Supervisión Prov.de Bibliotecas Escolares'],
            ['codigo' => '800', 'nombre' => 'Supervisor Nivel EGB3 y Polimodal'],
            ['codigo' => '801', 'nombre' => 'Dir.-/Rector 1ª Agricola.- T.C.'],
            ['codigo' => '802', 'nombre' => 'Dir.-/Rector 1ª .- T.C.'],
            ['codigo' => '803', 'nombre' => 'Dir.-/Rector 2ª .- T.C.'],
            ['codigo' => '804', 'nombre' => 'Dir.-/Rector 3ª .- T.C.'],
            ['codigo' => '805', 'nombre' => 'Dir.-/Rector 2ª .- T.S.'],
            ['codigo' => '806', 'nombre' => 'Dir.-/Rector 3ª .- T.S.'],
            ['codigo' => '807', 'nombre' => 'Vicedir./Vicered.1ª.- T.C.'],
            ['codigo' => '808', 'nombre' => 'Vicedir./Vicered.2ª.- T.C.'],
            ['codigo' => '809', 'nombre' => 'Vicedir./Vicered.3ª.- T.C.'],
            ['codigo' => '810', 'nombre' => 'Vicedir./Vicered.1ª.- T.S.'],
            ['codigo' => '811', 'nombre' => 'Vicedir./Vicered.2ª.- T.S.'],
            ['codigo' => '812', 'nombre' => 'Vicedir./Vicered.3ª.- T.S.'],
            ['codigo' => '813', 'nombre' => 'Secretario 1ª.- T.C.'],
            ['codigo' => '814', 'nombre' => 'Secretario 2ª.- T.C.'],
            ['codigo' => '815', 'nombre' => 'Secretario 3ª.- T.C.'],
            ['codigo' => '816', 'nombre' => 'Secretario 1ª.- T.S.'],
            ['codigo' => '817', 'nombre' => 'Secretario 2ª.- T.S.'],
            ['codigo' => '818', 'nombre' => 'Secretario 3ª.- T.S.'],
            ['codigo' => '819', 'nombre' => 'ProSecretario 1ª.- T.S.'],
            ['codigo' => '820', 'nombre' => 'ProSecretario 2ª.- T.S.'],
            ['codigo' => '821', 'nombre' => 'Coord. de Ciclo EGB 3.- T.C.'],
            ['codigo' => '822', 'nombre' => 'Coord. de Ciclo Polim. T.C.'],
            ['codigo' => '823', 'nombre' => 'Coord. de TAP.- T.C.'],
            ['codigo' => '824', 'nombre' => 'Coord. de Ciclo EGB 3.- T.S.'],
            ['codigo' => '825', 'nombre' => 'Coord. de Ciclo Polim. T.S.'],
            ['codigo' => '826', 'nombre' => 'Regente 1ª Ens. Técnica'],
            ['codigo' => '827', 'nombre' => 'Regente 3ª Ens. Técnica'],
            ['codigo' => '828', 'nombre' => 'Jefe Gral. Ens. Práctica 1ª'],
            ['codigo' => '829', 'nombre' => 'Coordinador Inter-Area'],
            ['codigo' => '830', 'nombre' => 'Coordinador de Area.'],
            ['codigo' => '831', 'nombre' => 'J. Sección Ens. Prác. Agricola- T.C.'],
            ['codigo' => '832', 'nombre' => 'Instructor Agricola.'],
            ['codigo' => '833', 'nombre' => 'Mtro. Ens. Práct. Ens. Técn.'],
            ['codigo' => '834', 'nombre' => 'Mtro. Ens. Práct. Jefe Sección.'],
            ['codigo' => '835', 'nombre' => 'Jefe de Area de TAP- T.S.'],
            ['codigo' => '836', 'nombre' => 'Jefe de Laboratorio.'],
            ['codigo' => '837', 'nombre' => 'Jefe PRCT 1ª-T.S.'],
            ['codigo' => '838', 'nombre' => 'Jefe PRCT 2ª-T.S.'],
            ['codigo' => '839', 'nombre' => 'SubJefe PRCT 1ª-T.S.'],
            ['codigo' => '840', 'nombre' => 'SubJefe PRCT 2ª-T.S.'],
            ['codigo' => '841', 'nombre' => 'Preceptor.-T.C.'],
            ['codigo' => '842', 'nombre' => 'Preceptor.-T.S.'],
            ['codigo' => '843', 'nombre' => 'Asesor Pedagógico (ASPD).'],
            ['codigo' => '844', 'nombre' => 'Ayud. Dpto. Orientación.'],
            ['codigo' => '845', 'nombre' => 'Psicoped. Dpto. Orien.'],
            ['codigo' => '846', 'nombre' => 'Auxiliar Administrativo Docente'],
            ['codigo' => '847', 'nombre' => 'Referente Institucional Informático'],
            ['codigo' => '848', 'nombre' => 'Ayud. Téc. Trabajos Prácticos (ATTP)'],
            ['codigo' => '849', 'nombre' => 'Ayudante Clases Prácticas.'],
            ['codigo' => '850', 'nombre' => 'Ayudante de Cátedra (Artística)'],
            ['codigo' => '851', 'nombre' => 'Bibliotecario. - T.S.'],
            ['codigo' => '852', 'nombre' => 'Hora Cátedra Nivel EGB 3 y polimod.'],
            ['codigo' => '853', 'nombre' => 'Prof. T.P. 02 24Hs.'],
            ['codigo' => '854', 'nombre' => 'Prof. T.P. 03 18Hs.'],
            ['codigo' => '855', 'nombre' => 'Mtro. Ens. Práct. Agricola.'],
            ['codigo' => '856', 'nombre' => 'Mtro. TUTOR-T.S.'],
            ['codigo' => '857', 'nombre' => 'Mtro. Cult. Rural/dom. Agricola.'],
            ['codigo' => '858', 'nombre' => 'Mtro. Especial (Artistica).'],
            ['codigo' => '859', 'nombre' => 'Coordinador T.T.P.-T.C.'],
            ['codigo' => '860', 'nombre' => 'Coordinador T.T.P.-T.S.'],
            ['codigo' => '861', 'nombre' => 'Coordinador T.A.P.-T.S.'],
            ['codigo' => '862', 'nombre' => 'Director Departamental de Bibliotecas'],
            ['codigo' => '863', 'nombre' => 'Vice Director Deptal. de Bibliotecas'],
            ['codigo' => '864', 'nombre' => 'Sec. Técn. Adm. Deptal. De Bibliotecas'],
            ['codigo' => '865', 'nombre' => 'Tutor T.I.y F.E.'],
            ['codigo' => '866', 'nombre' => 'Auxiliar de Secretaría T.S.'],
            ['codigo' => '867', 'nombre' => 'Auxiliar de Secretaría T.C.'],
            ['codigo' => '900', 'nombre' => 'Supervisor Nivel Terciario.'],
            ['codigo' => '901', 'nombre' => 'Dir.-/Rector 1 Turno'],
            ['codigo' => '902', 'nombre' => 'Vicedirector./Vicerector.'],
            ['codigo' => '903', 'nombre' => 'Jefe PRCT / BEDEL'],
            ['codigo' => '904', 'nombre' => 'Jefe de Laboratorio/Tráb Práctico.'],
            ['codigo' => '905', 'nombre' => 'Secretario'],
            ['codigo' => '906', 'nombre' => 'ProSecretario'],
            ['codigo' => '907', 'nombre' => 'Bibliotecario.'],
            ['codigo' => '908', 'nombre' => 'Preceptor.'],
            ['codigo' => '909', 'nombre' => 'Ayud. Téc. Trabajos Prácticos (ATTP)'],
            ['codigo' => '910', 'nombre' => 'Hora Cátedra'],
            ['codigo' => '949', 'nombre' => 'Supervisor Departamental de Bibliotecas'],
            ['codigo' => '950', 'nombre' => 'Supervisor General.'],
            ['codigo' => '951', 'nombre' => 'Super. de Areas Compl. (artística)'],
            ['codigo' => '952', 'nombre' => 'Super. de Areas Compl. (educ. físic.)'],
            ['codigo' => '953', 'nombre' => 'Supervisor de Bibliotecas.'],
            ['codigo' => '954', 'nombre' => 'Supervisor General de Nivel Secundario'],
            ['codigo' => '955', 'nombre' => 'Supervisor Escolar Departamental de Nivel Secundario'],
            ['codigo' => '956', 'nombre' => 'Supervisor Técnico Departamental de Nivel Secundario'],
            ['codigo' => '957', 'nombre' => 'Sup. Deptal. Lenguajes Artísticos N. Primario'],
            ['codigo' => '958', 'nombre' => 'Sup. Deptal. de Educación Física N. Primario'],
            ['codigo' => '959', 'nombre' => 'Sup. Deptal. de Tecnología Nivel Primario'],
        ];
        foreach ($cargos as $cargo) {
            Cargo::updateOrCreate(
                ['codigo' => $cargo['codigo']],
                ['nombre' => $cargo['nombre']]
            );
        }
    }
}
